name: 'Pull Request Labeler'
on:
  - pull_request_target

jobs:
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true
